### ISSUE TITLE
Error when execute npm install --save xlsx-writer

### ISSUE THREAD

**Issue by r2salgado** [rubenv/node-xlsx-writer#9]
Can you help me please?

make[1]: Entering directory '/home/asalgado/projects/testUnam/app/node_modules/xlsx-writer/node_modules/zipper/build'
  CXX(target) Release/obj.target/zipper/src/_zipper.o
In file included from ../src/_zipper.cc:9:0:
../src/zipper.hpp:25:36: error: ‘Arguments’ does not name a type
     static Handle<Value> New(const Arguments &args);
                                    ^
../src/zipper.hpp:28:40: error: ‘Arguments’ does not name a type
     static Handle<Value> addFile(const Arguments& args);
                                        ^
../src/zipper.hpp:29:26: error: ‘uv_work_t’ has not been declared
     static void _AddFile(uv_work_t *req);
                          ^
../src/zipper.hpp:30:31: error: ‘uv_work_t’ has not been declared
     static void _AfterAddFile(uv_work_t *req);
                               ^
../src/_zipper.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/_zipper.cc:22:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                 ^
../src/_zipper.cc:22:47: error: ‘New’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("version"), String::New("0.0.1"));
                                               ^
../src/_zipper.cc:25:42: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> versions = Object::New();
                                          ^
In file included from ../src/_zipper.cc:2:0:
/home/asalgado/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/asalgado/.node-gyp/0.12.7/deps/v8/include/v8.h:2388:24: note:   candidate expects 1 argument, 0 provided
../src/_zipper.cc:26:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
     versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                   ^
../src/_zipper.cc:26:46: error: ‘New’ is not a member of ‘v8::String’
     versions->Set(String::NewSymbol("node"), String::New(NODE_VERSION+1));
                                              ^
../src/_zipper.cc:27:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
     versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                   ^
../src/_zipper.cc:27:44: error: ‘New’ is not a member of ‘v8::String’
     versions->Set(String::NewSymbol("v8"), String::New(V8::GetVersion()));
                                            ^
../src/_zipper.cc:28:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(String::NewSymbol("versions"), versions);
                 ^
zipper.target.mk:87: recipe for target 'Release/obj.target/zipper/src/_zipper.o' failed
make[1]: *** [Release/obj.target/zipper/src/_zipper.o] Error 1
make[1]: Leaving directory '/home/asalgado/projects/testUnam/app/node_modules/xlsx-writer/node_modules/zipper/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.0.8-300.fc22.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/asalgado/projects/testUnam/app/node_modules/xlsx-writer/node_modules/zipper
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
Makefile:22: recipe for target 'lib/_zipper.node' failed
make: *** [lib/_zipper.node] Error 1
npm ERR! Linux 4.0.8-300.fc22.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "xlsx-writer"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! zipper@0.3.0 install: `make all`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the zipper@0.3.0 install script 'make all'.
npm ERR! This is most likely a problem with the zipper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make all
npm ERR! You can get their info via:
npm ERR!     npm owner ls zipper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/asalgado/projects/testUnam/app/node_modules/npm-debug.log

**Comment by Silve2611** [comment]
Same Problem here. Is the error because of the newer version of node?
